options:
  logging: CLOUD_LOGGING_ONLY

steps:

# 1️⃣ Build Spring Boot jar
- name: 'maven:3.9.6-eclipse-temurin-17'
  entrypoint: mvn
  args: ['clean', 'package', '-DskipTests']

# 2️⃣ Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/stamps-repo/stamps-app',
      '.'
    ]

# 3️⃣ Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/stamps-repo/stamps-app'
    ]

# 4️⃣ Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    [
      'run',
      'deploy',
      'stamps',
      '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/stamps-repo/stamps-app',
      '--region=asia-south1',
      '--platform=managed',
      '--allow-unauthenticated',
      '--add-cloudsql-instances=project-5176d167-2b21-4712-a35:asia-south1:demoprojectdb'
    ]

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/stamps-repo/stamps-app